#!/usr/bin/env python3
"""Generate convex-decomposition collision meshes with CoACD.

Usage (from the workspace root; needs `pip install coacd trimesh`):
    python3 ranger_xarm6_description/scripts/generate_colliders.py            # all meshes in MESHES
    python3 ranger_xarm6_description/scripts/generate_colliders.py extras_compressed

For each source mesh in meshes/, writes meshes/collision/<name>/<name>_NN.stl
(one convex hull per file, same units and frame as the source, so the
visual's own <origin>/scale applies unchanged) and regenerates
robots/_colliders.xacro, which defines one macro per mesh:
    <xacro:collider_<name> xyz="..." rpy="..." scale="..." />
emitting one <collision> element per hull.

One <collision> per hull, not a single merged STL: MoveIt's FCL and Gazebo
both treat a mesh collider as a triangle soup whatever its shape, so the
hulls only get treated as convex pieces when kept separate.

threshold is CoACD's concavity tolerance (lower = tighter fit, more hulls);
max_hulls caps the count (-1 = no cap, CoACD merges hulls down to it).
CoACD's own hulls keep every original vertex on their surface (18k tris
for the Livox alone), so each is simplified (see simplify_hull).
"""
import os
import sys

import coacd
import numpy as np
import trimesh

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MESH_DIR = os.path.join(PKG, 'meshes')
OUT_DIR = os.path.join(MESH_DIR, 'collision')
XACRO = os.path.join(PKG, 'robots', '_colliders.xacro')
# Vertex budget per hull (see simplify_hull): <= 2x this many triangles.
SUPPORT_DIRS = 256

MESHES = {
    # name (meshes/<name>.stl): CoACD settings
    'extras_compressed': {'threshold': 0.03, 'max_hulls': 64},
    'xarm_mount_plate': {'threshold': 0.05, 'max_hulls': 16},
    'livox_imu_mount': {'threshold': 0.05, 'max_hulls': 16},
    'hipnuc_imu': {'threshold': 0.05, 'max_hulls': 12},
    'livox_mid_360': {'threshold': 0.05, 'max_hulls': 8},
}


def simplify_hull(hull):
    """Cut an over-dense convex hull down to at most SUPPORT_DIRS vertices.

    For SUPPORT_DIRS directions spread evenly over the sphere, keep the
    hull vertex furthest along each one (its support point), then re-hull
    that subset. The result is a hull of real vertices, so it stays
    well-conditioned (quadric decimation instead moved the surface inward
    by up to 8.8mm on livox_imu_mount); it can only shrink between kept
    vertices, by a fraction of a mm on curved surfaces like the Livox dome.
    Hulls already under 2 * SUPPORT_DIRS faces are left untouched.
    """
    if len(hull.faces) <= 2 * SUPPORT_DIRS:
        return hull
    i = np.arange(SUPPORT_DIRS) + 0.5
    phi = np.arccos(1 - 2 * i / SUPPORT_DIRS)
    theta = np.pi * (1 + 5 ** 0.5) * i
    dirs = np.c_[np.cos(theta) * np.sin(phi), np.sin(theta) * np.sin(phi), np.cos(phi)]
    keep = np.unique(np.argmax(hull.vertices @ dirs.T, axis=0))
    return trimesh.convex.convex_hull(hull.vertices[keep])


def decompose(name, threshold, max_hulls):
    src = trimesh.load(os.path.join(MESH_DIR, f'{name}.stl'), force='mesh')
    parts = coacd.run_coacd(
        coacd.Mesh(src.vertices, src.faces),
        threshold=threshold,
        max_convex_hull=max_hulls,
        preprocess_mode='auto',
        seed=0,
    )
    out = os.path.join(OUT_DIR, name)
    os.makedirs(out, exist_ok=True)
    for f in os.listdir(out):
        if f.endswith('.stl'):
            os.remove(os.path.join(out, f))
    total = 0
    for i, (v, f) in enumerate(parts):
        hull = simplify_hull(trimesh.Trimesh(np.asarray(v), np.asarray(f)).convex_hull)
        hull.export(os.path.join(out, f'{name}_{i:02d}.stl'))
        total += len(hull.faces)
    print(f'{name}: {len(src.faces)} tris -> {len(parts)} hulls, {total} tris')


def write_xacro():
    lines = [
        '<?xml version="1.0"?>',
        '<!-- GENERATED by scripts/generate_colliders.py: do not edit by hand. -->',
        '<robot xmlns:xacro="http://www.ros.org/wiki/xacro">',
    ]
    for name in MESHES:
        d = os.path.join(OUT_DIR, name)
        hulls = sorted(f for f in os.listdir(d) if f.endswith('.stl')) if os.path.isdir(d) else []
        lines.append(f'  <xacro:macro name="collider_{name}" params="xyz:=\'0 0 0\' rpy:=\'0 0 0\' scale:=\'1 1 1\'">')
        for h in hulls:
            lines += [
                '    <collision>',
                '      <origin xyz="${xyz}" rpy="${rpy}" />',
                '      <geometry>',
                f'        <mesh filename="package://ranger_xarm6_description/meshes/collision/{name}/{h}" scale="${{scale}}" />',
                '      </geometry>',
                '    </collision>',
            ]
        lines.append('  </xacro:macro>')
    lines.append('</robot>')
    with open(XACRO, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'wrote {XACRO}')


if __name__ == '__main__':
    names = sys.argv[1:] or list(MESHES)
    for n in names:
        decompose(n, **MESHES[n])
    write_xacro()
