#!/usr/bin/env python3
"""Generate the SRDF <disable_collisions> block from the robot's URDF.

Usage (from the workspace root, after building ranger_xarm6_description):
    xacro ranger_xarm6_description/robots/ranger_xarm6.urdf.xacro > /tmp/r.urdf
    python3 ranger_xarm6_moveit_config/scripts/generate_collision_matrix.py /tmp/r.urdf

Writes ranger_xarm6_moveit_config/srdf/_disable_collisions.srdf.xacro, a
xacro macro taking the same 'prefix' the URDF uses. Stands in for the MoveIt
Setup Assistant's collision matrix, but reproducible and conservative: it
only disables pairs that can never collide in a meaningful way, and never
the Setup Assistant's sample-based "Never" pairs (those can hide real
collisions after hardware changes, e.g. the F/T sensor stack moving the
gripper 88mm further from link6 than xArm's own SRDF assumes).

A pair is disabled when:
  - Adjacent: the two links are joined by a single joint, skipping over
    links that have no collision geometry (same rule as the Setup
    Assistant).
  - Rigid: the two links can never move relative to each other during
    planning, i.e. they're connected only through fixed joints or passive,
    non-mimic joints (the Ranger's wheel/steering joints: published in
    /joint_states but never planned, so they're effectively frozen).
  - Listed in config/collision_overrides.yaml: pairs found to collide in
    every sampled state by scripts/sample_self_collisions.py (touching or
    overlapping meshes), each reviewed by hand before being added there.
"""
import itertools
import os
import sys
import xml.etree.ElementTree as ET

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
OUT = os.path.join(PKG, 'srdf', '_disable_collisions.srdf.xacro')
OVERRIDES = os.path.join(PKG, 'config', 'collision_overrides.yaml')

# Joints MoveIt never plans for (must match the SRDF's passive_joint list),
# without the prefix. Mimic joints are NOT listed: they move with
# drive_joint whenever the gripper group is planned.
PASSIVE_JOINTS = [
    f'{corner}_{kind}' for corner in ('fr', 'fl', 'rl', 'rr')
    for kind in ('steering_joint', 'wheel')
]


def strip_prefix(name, prefix):
    return name[len(prefix):] if prefix and name.startswith(prefix) else name


def main(urdf_path, prefix):
    root = ET.parse(urdf_path).getroot()
    has_geom = {
        strip_prefix(l.get('name'), prefix): l.find('collision') is not None
        for l in root.findall('link')
    }
    parent_of = {}   # child link -> (parent link, joint rigid?)
    for j in root.findall('joint'):
        child = strip_prefix(j.find('child').get('link'), prefix)
        parent = strip_prefix(j.find('parent').get('link'), prefix)
        name = strip_prefix(j.get('name'), prefix)
        rigid = j.get('type') == 'fixed' or name in PASSIVE_JOINTS
        parent_of[child] = (parent, rigid)

    def collision_parent(link):
        """Nearest ancestor with collision geometry, and whether every joint
        on the way there is rigid."""
        rigid = True
        while link in parent_of:
            link, joint_rigid = parent_of[link]
            rigid = rigid and joint_rigid
            if has_geom[link]:
                return link, rigid
        return None, rigid

    def rigid_root(link):
        while link in parent_of and parent_of[link][1]:
            link = parent_of[link][0]
        return link

    geom_links = sorted(l for l, g in has_geom.items() if g)
    pairs = {}
    for link in geom_links:
        parent, _ = collision_parent(link)
        if parent:
            pairs[tuple(sorted((link, parent)))] = 'Adjacent'
    for a, b in itertools.combinations(geom_links, 2):
        if rigid_root(a) == rigid_root(b):
            pairs.setdefault(tuple(sorted((a, b))), 'Rigid')

    if os.path.exists(OVERRIDES):
        with open(OVERRIDES) as f:
            for entry in (yaml.safe_load(f) or {}).get('disable', []):
                a, b = entry['links']
                pairs.setdefault(tuple(sorted((a, b))), entry.get('reason', 'Override'))

    lines = [
        '<?xml version="1.0"?>',
        '<!-- GENERATED by scripts/generate_collision_matrix.py: do not edit by hand. -->',
        '<robot xmlns:xacro="http://www.ros.org/wiki/xacro">',
        '  <xacro:macro name="ranger_xarm6_disable_collisions" params="prefix">',
    ]
    for (a, b), reason in sorted(pairs.items()):
        lines.append(
            f'    <disable_collisions link1="${{prefix}}{a}" link2="${{prefix}}{b}" reason="{reason}" />')
    lines += ['  </xacro:macro>', '</robot>', '']
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))
    counts = {}
    for reason in pairs.values():
        counts[reason] = counts.get(reason, 0) + 1
    print(f'{len(geom_links)} links with collision geometry, '
          f'{len(geom_links) * (len(geom_links) - 1) // 2} pairs; disabled {counts}')
    print(f'wrote {OUT}')


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else '')
